#!/bin/bash
#export GPU_FORCE_64BIT_PTR=0
#export GPU_MAX_HEAP_SIZE=100
#export GPU_USE_SYNC_OBJECTS=1
#export GPU_MAX_ALLOC_PERCENT=100
#export GPU_SINGLE_ALLOC_PERCENT=100

#nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffset[3]=100'
#nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffset[3]=1000'
#nvidia-settings -a '[gpu:0]/GPUFanControlState=1'
#nvidia-settings -a '[fan:0]/GPUTargetFanSpeed=75'

#nvidia-settings -a '[gpu:1]/GPUGraphicsClockOffset[3]=100'
#nvidia-settings -a '[gpu:1]/GPUMemoryTransferRateOffset[3]=1000'
#nvidia-settings -a '[gpu:1]/GPUFanControlState=1'
#nvidia-settings -a '[fan:1]/GPUTargetFanSpeed=75'

#nvidia-settings -a '[gpu:2]/GPUGraphicsClockOffset[3]=100'
#nvidia-settings -a '[gpu:2]/GPUMemoryTransferRateOffset[3]=1000'
#nvidia-settings -a '[gpu:2]/GPUFanControlState=1'
#nvidia-settings -a '[fan:2]/GPUTargetFanSpeed=75'

#nvidia-settings -a '[gpu:3]/GPUGraphicsClockOffset[3]=100'
#nvidia-settings -a '[gpu:3]/GPUMemoryTransferRateOffset[3]=1000'
#nvidia-settings -a '[gpu:3]/GPUFanControlState=1'
#nvidia-settings -a '[fan:3]/GPUTargetFanSpeed=75'

#nvidia-settings -a '[gpu:4]/GPUGraphicsClockOffset[3]=100'
#nvidia-settings -a '[gpu:4]/GPUMemoryTransferRateOffset[3]=1000'
#nvidia-settings -a '[gpu:4]/GPUFanControlState=1'
#nvidia-settings -a '[fan:4]/GPUTargetFanSpeed=75'

#nvidia-settings -a '[gpu:5]/GPUGraphicsClockOffset[3]=100'
#nvidia-settings -a '[gpu:5]/GPUMemoryTransferRateOffset[3]=1000'
#nvidia-settings -a '[gpu:5]/GPUFanControlState=1'
#nvidia-settings -a '[fan:5]/GPUTargetFanSpeed=75'

ethminer --farm-recheck 200 -U \
		-v 9 \
		-S eth-asia1.nanopool.org:9999 \
		-FS eth-us-west1.nanopool.org:9999 \
		-O 0xC71c4d0675Bf6D12C8A08d449d4966562eb3e88A.gpuminer2/galahade@sina.com
