#!/bin/bash

export GPU_FORCE_64BIT_PTR 0
export GPU_MAX_HEAP_SIZE 100
export GPU_USE_SYNC_OBJECTS 1
export GPU_MAX_ALLOC_PERCENT 100
export GPU_SINGLE_ALLOC_PERCENT 100

sudo nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffset[3]=100'
sudo nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffset[3]=1000'
sudo nvidia-settings -a '[gpu:0]/GPUFanControlState=1' 
sudo nvidia-settings -a '[fan:0]/GPUTargetFanSpeed=70'

ethminer --farm-recheck 200 -U \
		-S eth-asia1.nanopool.org:9999 \
		-FS eth-us-west1.nanopool.org:9999 \
		-O 0xC71c4d0675Bf6D12C8A08d449d4966562eb3e88A.gpuminer2/galahade@sina.com
