#!/bin/bash

echo 'clocks.current.video -- current frequency of video encoder/decoder clock.\n'
echo 'clocks.current.sm -- current frequency of SM (Streaming Multiprocessor) clock.\n'
echo 'clocks.current.memory -- current frequency of memory clock.\n'
echo 'clocks.current.graphics -- current frequency of graphics (shader) clock.\n'

$ nvidia-smi --format=csv\
		 --query-gpu=fan.speed,\
		 temperature.gpu,\
		 clocks.current.video,\
		 clocks.current.sm,\
		 clocks.current.memory,\
		 clocks.current.graphics,\
		 clocks.max.sm,\
		 clocks.max.memory,\
		 clocks.max.graphics,\