#!/bin/bash

echo 'clocks.current.video -- current frequency of video encoder/decoder clock.'
echo 'clocks.current.sm -- current frequency of SM (Streaming Multiprocessor) clock.'
echo 'clocks.current.memory -- current frequency of memory clock.'

nvidia-smi --format=csv\
		 --query-gpu=fan.speed,temperature.gpu,clocks.current.video,clocks.current.sm,clocks.current.memory,clocks.max.sm,clocks.max.memory