#!/bin/bash

sudo -i

echo 5 > /sys/class/drm/card0/device/pp_sclk_od
echo 5 > /sys/class/drm/card1/device/pp_sclk_od
echo 5 > /sys/class/drm/card2/device/pp_sclk_od
echo 5 > /sys/class/drm/card3/device/pp_sclk_od
echo 5 > /sys/class/drm/card4/device/pp_sclk_od
echo 5 > /sys/class/drm/card5/device/pp_sclk_od

echo 10 > /sys/class/drm/card0/device/pp_mclk_od
echo 10 > /sys/class/drm/card1/device/pp_mclk_od
echo 10 > /sys/class/drm/card2/device/pp_mclk_od
echo 10 > /sys/class/drm/card3/device/pp_mclk_od
echo 10 > /sys/class/drm/card4/device/pp_mclk_od
echo 10 > /sys/class/drm/card5/device/pp_mclk_od


cat /sys/kernel/debug/dri/0/amdgpu_pm_info
cat /sys/kernel/debug/dri/1/amdgpu_pm_info
cat /sys/kernel/debug/dri/2/amdgpu_pm_info
cat /sys/kernel/debug/dri/3/amdgpu_pm_info
cat /sys/kernel/debug/dri/4/amdgpu_pm_info
cat /sys/kernel/debug/dri/5/amdgpu_pm_info